<?php declare(strict_types=1);
/**
 * Created by PhpStorm.
 * User: Lukasz
 */

namespace Tests\Unit\app\Repositories\Film;


use App\Repositories\Film\FilmRepository;
use App\Services\StarWars\Response\Films\FilmsItemResponse;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Src\RepositoriesAbstract\Film\IFilmRepository;
use Tests\TestCase;
use Tests\Unit\app\Logic\StarWars\DataMap;

class FilmRepositoryTest extends TestCase
{
    use RefreshDatabase;

    /** @var FilmRepository */
    private $filmRepository;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->filmRepository = app(IFilmRepository::class);
    }

    /** @test */
    public function saveByFilmItemResponse_correct()
    {
        /** @var FilmsItemResponse $filmItemResponse */
        $filmItemResponse = DataMap::map(DataMap::getFilmsItem(), new FilmsItemResponse());

        $film = $this->filmRepository->saveByFilmItemResponse($filmItemResponse);

        $this->assertNotNull($film->id);
        $this->assertSame($filmItemResponse->title, $film->title);
        $this->assertSame($filmItemResponse->episode_id, $film->episode_id);
        $this->assertSame($filmItemResponse->opening_crawl, $film->opening_crawl);

        $this->assertDatabaseHas('films', [
            'title' => $filmItemResponse->title,
            'episode_id' => $filmItemResponse->episode_id,
            'opening_crawl' => $filmItemResponse->opening_crawl
        ]);
    }
}