<?php declare(strict_types=1);
/**
 * Created by PhpStorm.
 * User: Lukasz
 */

namespace Tests\Unit\app\Logic\StarWars\Film;


use App\Logic\StarWars\Film\FilmStarWarsLogic;
use App\Services\StarWars\Request\FilmsRequest;
use GuzzleHttp\Client;
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Psr7\Response;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Tests\Unit\app\Logic\StarWars\ClientServiceProvider;
use Tests\Unit\app\Logic\StarWars\DataMap;

class FilmStarWarsLogicNotFoundTest extends TestCase
{
    use RefreshDatabase, ClientServiceProvider;

    /** @var FilmStarWarsLogic */
    protected $filmLogic;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $mock = new MockHandler([
            new Response(200, [], DataMap::getNotFound())
        ]);

        $handler = HandlerStack::create($mock);

        $this->initClient($handler);

        $this->filmLogic = app(FilmStarWarsLogic::class);
    }

    /** @test */
    public function getByUrlAndSave_wrong_url()
    {
        $film = $this->filmLogic->getByUrlAndSave('asd/1000/');

        $this->assertNull($film->id);
        $this->assertNull($film->title);
        $this->assertNull($film->episode_id);
    }
}